### ISSUE TITLE
Server logging

### ISSUE THREAD

**Issue by Gervwyk** [lowdefy/lowdefy#688]
Turn on more detailed dev server logging and error messages.

**Comment by APTy** [comment]
A few things that'd be nice to see in a verbose logging mode:

1. Any HTTP/DB calls that are made and their details. So URLs, headers, request/response body.
2. Printing when blocks/operators/actions are invalid. A lot of these things fail silently, for example if you pass the wrong arg type to a function, or if you have typos in field names (i.e. providing a `header` instead of `headers` property in yaml).
