### ISSUE TITLE
Input Blocks display empty instead of 0 when the state is 0

### ISSUE THREAD

**Issue by 13316090972** [lowdefy/lowdefy#735]
the input blocks (TextInput,TitleInput etc.) display empty when the state equals zero.
codes like bellow:

        - id: setNumericObj
          type: SetState
          params:
              blockId1: 0
              blockId2: 1
              blockId3: 3

       - id: blockId1
         type: TitleInput
       - id: blockId2
         type: TitleInput
       - id: blockId3
         type: TitleInput
![state0](https://user-images.githubusercontent.com/56707831/129177090-2142e0f8-6661-4561-bf41-ee9e05f9c4f3.png)

**Comment by Gervwyk** [comment]
Hi @13316090972 
Thanks for reporting this bug. It's because of line: https://github.com/lowdefy/lowdefy/blob/4bc9430407e4ba59bf3940a8406173899190da3f/packages/blocks/blocksAntd/src/blocks/TitleInput/TitleInput.js#L127

To remedy this, for now, you can make sure that you set the values as a string instead of a number zero, like so:
```
 id: setNumericObj
 type: SetState
 params:
    blockId1: '0'
    blockId2: '1'
    blockId3: '3'
```
Will add a fix for this in next release.
